config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"

  resources :movies do
    resources :comments, only: [:edit, :update, :new, :create]
  end
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params.merge(movie_id: params[:movie_id], user_id: current_user.id))
    if @comment.save
      redirect_to movie_path(params[:movie_id])
    else
      render :new
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to movie_path(@comment.movie)
    else
      render :edit
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @comments = Comment.where(movie_id: params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params.merge(user_id: current_user.id))
    if @movie.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    Movie.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :description, :runtime, :released, :genre, :actors, :director,
                                  :imdb_rating, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:image, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<%= form_with model: @comment, url: movie_comment_path do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<%= form_with model: @comment, url: movie_comments_path do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= link_to 'New Movie', new_movie_path %>
  <%= link_to 'Edit Profile', edit_user_path(current_user) %>
  <%= button_to 'Exit', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Film</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<%= form_with model: @movie, url: movie_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :released %>
  <%= f.date_field :released %>

  <%= f.label :runtime %>
  <%= f.text_field :runtime %>

  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :actors %>
  <%= f.text_field :actors %>

  <%= f.label :director %>
  <%= f.text_field :director %>

  <%= f.label :imdb_rating %>
  <%= f.text_field :imdb_rating %>

  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <p><%= movie.title %></p>
  <p><%= movie.description %></p>
  <%= link_to 'Show', movie_path(movie), class: 'btn btn-dark' %>
  <%= link_to 'Edit', edit_movie_path(movie), class: 'btn btn-dark' if current_user == movie.user %>
<% end %>

app/views/movies/new.html.erb
<%= form_with model: @movie, url: movies_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :released %>
  <%= f.date_field :released %>
  
  <%= f.label :runtime %>
  <%= f.text_field :runtime %>
  
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  
  <%= f.label :description %>
  <%= f.text_area :description %>
  
  <%= f.label :actors %>
  <%= f.text_field :actors %>

  <%= f.label :director %>
  <%= f.text_field :director %>
  
  <%= f.label :imdb_rating %>
  <%= f.text_field :imdb_rating %>

  <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<%= @movie.title %>
<p><b>Released:</b> <%= @movie.released %></p>
<p><b>IMDB Rating:</b> <%= @movie.imdb_rating %></p>
<p><b>Genre:</b> <%= @movie.genre %></p>
<p><b>Runtime:</b> <%= @movie.runtime %></p>
<p><b>Actors:</b> <%= @movie.actors %></p>
<p><b>Director:</b> <%= @movie.director %></p>
<p><%= @movie.description %></p>
<%= link_to 'Edit', edit_movie_path(@movie) %>
<%= button_to 'Delete', movie_path(@movie), method: :delete %>
<%= link_to 'add comment', new_movie_comment_path(@movie) if user_signed_in? %>
<% @comments.each do |comment| %>
  <br>
  <%= comment.user.email %>
  <br>
  <%= comment.body %>
  <br>
  <%= link_to 'Edit comment', edit_movie_comment_path(@movie, comment) if current_user == comment.user %>
<% end %>

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_path do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :avater %>
  <%= f.file_field :avater %>

  <%= f.submit %>
<% end %>